server.port: 8999
eureka.instance:hostname: localhost

spring.application.name: api-gateway
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**



